"""Choose the embedding model with grouped cross-validation (test set untouched).

Candidates are embedded by `node scripts/embed_phrases.mjs <model> <prefix> <tag>`. For each, a softmax
regression is scored with 5-fold StratifiedGroupKFold over the clear train+validation families (a family
is never split across folds), with C chosen per candidate. The keyword baseline and char TF-IDF are scored
on the same folds for reference. Writes reports/embedding_comparison.md.

Why cross-validation: validation alone is 84 clear phrases in 14 families, so one family flipping moves
accuracy ~7 points. Grouped CV scores all 432 train+validation phrases once each.
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import StratifiedGroupKFold

import keyword_baseline
from split import MANIFEST, load

ROOT = Path(__file__).resolve().parent.parent
PROC = ROOT / "data" / "processed"
REPORT = ROOT / "reports" / "embedding_comparison.md"

CANDIDATES = {  # tag -> (model, quantized size MB, fits Vercel's 250 MB function limit)
    "e5small": ("Xenova/multilingual-e5-small", 118, True),
    "pmini": ("Xenova/paraphrase-multilingual-MiniLM-L12-v2", 118, True),
    "distiluse": ("Xenova/distiluse-base-multilingual-cased-v2", 135, True),
    "labse": ("Xenova/LaBSE", 472, False),
    # Served from AWS Bedrock: no size limit, but a network call per message (see latency columns)
    "titan1024": ("bedrock/amazon.titan-embed-text-v2:0 @1024", None, True),
    "titan512": ("bedrock/amazon.titan-embed-text-v2:0 @512", None, True),
    "cohere-mv3": ("bedrock/cohere.embed-multilingual-v3", None, True),
}
C_GRID = [0.3, 1, 3, 10, 30, 100, 300]
SEED = 2026


def load_emb(tag, ids):
    meta = json.loads((PROC / f"phrase_embeddings_{tag}.json").read_text())
    X = np.fromfile(PROC / f"phrase_embeddings_{tag}.f32", dtype=np.float32).reshape(meta["rows"], meta["dims"])
    order = {p: i for i, p in enumerate(meta["ids"])}
    return X[[order[i] for i in ids]], meta


def cv_scores(fit_predict, y, groups, folds):
    preds = np.empty(len(y), dtype=object)
    per_fold = []
    for tr, te in folds:
        preds[te] = fit_predict(tr, te)
        per_fold.append((preds[te] == y[te]).mean())
    return {"accuracy": (preds == y).mean(), "macro_f1": f1_score(y, preds, average="macro"),
            "fold_sd": np.std(per_fold), "pred": preds}


def main():
    df, _, _ = load()
    manifest = json.loads(MANIFEST.read_text())
    df["split"] = df.family.map(manifest["families"])
    dev = df[(df.split != "test") & ~df.ambiguous].reset_index(drop=True)
    y, groups = dev.label.values, dev.family.values
    folds = list(StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=SEED).split(dev, y, groups))

    rows = []
    kw = cv_scores(lambda tr, te: np.array([keyword_baseline.predict(t) for t in dev.text[te]]), y, groups, folds)
    rows.append({"candidate": "keyword rules", "C": "-", **{k: v for k, v in kw.items() if k != "pred"}})

    def tfidf_fp(C):
        def fp(tr, te):
            vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(2, 5), sublinear_tf=True).fit(dev.text[tr])
            m = LogisticRegression(C=C, max_iter=5000).fit(vec.transform(dev.text[tr]), y[tr])
            return m.predict(vec.transform(dev.text[te]))
        return fp
    best = max((cv_scores(tfidf_fp(C), y, groups, folds) | {"C": C} for C in C_GRID), key=lambda r: r["macro_f1"])
    rows.append({"candidate": "char TF-IDF", **{k: v for k, v in best.items() if k != "pred"}})

    by_lang = {}
    for tag, (model, size, fits) in CANDIDATES.items():
        if not (PROC / f"phrase_embeddings_{tag}.json").exists():
            print(f"skipping {tag}: not embedded yet")
            continue
        X, meta = load_emb(tag, dev.phrase_id)

        def emb_fp(C, X=X):
            return lambda tr, te: LogisticRegression(C=C, max_iter=5000).fit(X[tr], y[tr]).predict(X[te])
        results = [cv_scores(emb_fp(C), y, groups, folds) | {"C": C} for C in C_GRID]
        best = max(results, key=lambda r: r["macro_f1"])
        by_lang[tag] = {lang: round(float((best["pred"][dev.lang.values == lang] == y[dev.lang.values == lang]).mean()), 3)
                        for lang in ["es", "pt"]}
        where = (f"{size} MB{'' if fits else ', too big for Vercel'}" if size
                 else f"Bedrock API, p50 {meta['latency_ms']['p50']:.0f} ms/message")
        rows.append({"candidate": f"{model.split('/', 1)[1]} ({meta['dims']}d, {where})",
                     **{k: v for k, v in best.items() if k != "pred"}, "es": by_lang[tag]["es"], "pt": by_lang[tag]["pt"]})

    res = pd.DataFrame(rows)
    with REPORT.open("w") as f:
        f.write("# Embedding model comparison (grouped 5-fold CV, test set untouched)\n\n")
        f.write(f"_Generated by `pipeline/compare_embeddings.py`. {len(dev)} clear train+validation phrases in "
                f"{dev.family.nunique()} families; folds never split a family. Classifier: softmax regression, "
                "C chosen per candidate by macro-F1._\n\n")
        f.write(res.round(3).to_markdown(index=False) + "\n")
    print(res.round(3).to_string(index=False))


if __name__ == "__main__":
    main()
