"""How the intent model's confidence threshold depends on the cost weights (docs/intent-model.md D11).

The threshold is the confidence below which the assistant asks instead of acting. train_intent.py picks it by
minimizing the mean cost of decisions on validation, with weights wrong action = 5, acting on an ambiguous message = 2,
needless question = 1, which D11 calls "an assumption, not a measurement". This re-runs that choice under other weights
and reports the threshold each picks and what it does on validation.

Validation only, like the choice it re-runs: the sealed test set is never read (no --test, nothing appended to
reports/test_runs.jsonl). The model is fitted exactly as train_intent.py fits it (same C selection, same split).

Usage: (cd pipeline && uv run python cost_sensitivity.py [--embedding e5small|cohere-mv3])
Writes reports/cost_sensitivity_<embedding>.md
"""
import argparse
import json
from datetime import datetime, timezone

import numpy as np

import train_intent as ti

WRONG_ACTION = [2, 3, 5, 10, 20]
ACTED_ON_AMBIGUOUS = [1, 2, 3]
NEEDLESS_QUESTION = 1  # the unit: every other cost is relative to one needless question
NEAR = 0.01  # thresholds within this much of the minimum mean cost count as "near-optimal"


def mean_cost(conf, pred, df_part, t, w_wrong, w_amb, w_needless):
    """train_intent.decision_cost, with the weights as parameters."""
    act = conf >= t
    amb = df_part.ambiguous.values
    wrong = pred != df_part.label.values
    cost = np.where(amb, np.where(act, w_amb, 0), np.where(act, np.where(wrong, w_wrong, 0), w_needless))
    return cost.mean()


def choose(conf, pred, df_part, weights):
    """train_intent.select_threshold: lowest threshold at the minimum cost; plus the near-optimal band."""
    costs = [(round(mean_cost(conf, pred, df_part, t, *weights), 5), float(t)) for t in ti.THRESHOLDS]
    best = min(c for c, _ in costs)
    near = [t for c, t in costs if c <= best + NEAR]
    return min(t for c, t in costs if c == best), best, (min(near), max(near))


def pct(v):
    return "n/a" if v is None or (isinstance(v, float) and np.isnan(v)) else f"{100 * v:.1f}%"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--embedding", default="e5small", choices=list(ti.EMBEDDINGS))
    args = ap.parse_args()

    df, X, _, _ = ti.get_data(args.embedding)  # refuses to run if the sealed test set changed
    tr, va = (df.split == "train").values, (df.split == "validation").values
    C, _ = ti.select_C(lambda a, b: (X[a], X[b]), df)
    model = ti.fit_lr(X[tr], df.label.values[tr], C)
    proba = model.predict_proba(X[va])
    conf, pred = proba.max(1), model.classes_[proba.argmax(1)]
    df_va = df[va]

    # Self-check: at the current weights this must pick exactly what train_intent.py picks.
    current = (ti.COST_WRONG_ACTION, ti.COST_ACTED_ON_AMBIGUOUS, ti.COST_NEEDLESS_QUESTION)
    ours, _, _ = choose(conf, pred, df_va, current)
    theirs, _ = ti.select_threshold(proba, model.classes_, df_va)
    if ours != theirs:
        raise SystemExit(f"threshold mismatch with train_intent.py at {current}: {ours} vs {theirs}; refusing to report")

    served = ti.ROOT / "src" / "lib" / f"intent-model-{args.embedding}.json"
    served_t = json.loads(served.read_text())["threshold"] if served.exists() else None

    rows = []
    for w_wrong in WRONG_ACTION:
        for w_amb in ACTED_ON_AMBIGUOUS:
            weights = (w_wrong, w_amb, NEEDLESS_QUESTION)
            t, cost, band = choose(conf, pred, df_va, weights)
            m = ti.decision_metrics(pred, conf, df_va, t)
            rows.append({"weights": weights, "threshold": t, "cost": cost, "band": band, **m})

    chosen = sorted({r["threshold"] for r in rows})
    lines = [
        f"# Intent threshold vs. cost weights ({args.embedding})", "",
        f"_Generated by `pipeline/cost_sensitivity.py` on {datetime.now(timezone.utc).isoformat(timespec='seconds')} "
        f"(commit {ti.git_commit()}). Do not edit by hand. Validation set only ({int(va.sum())} phrases, "
        f"{int((~df_va.ambiguous).sum())} clear + {int(df_va.ambiguous.sum())} ambiguous); the sealed test set is not read._", "",
        "The assistant acts when the model's confidence is at least the threshold, and asks otherwise. `train_intent.py` picks "
        "the threshold that minimizes the mean cost of these decisions on validation, with weights wrong action 5, acting on an "
        "ambiguous message 2, needless question 1 (D11: \"an assumption, not a measurement\"). This table re-runs that choice "
        f"under other weights, on the same model (C = {C}, refitted the same way; at 5 / 2 / 1 it picks exactly what "
        "`train_intent.py` picks).", "",
        f"**Thresholds chosen across the grid: {', '.join(f'{t:.2f}' for t in chosen)}.**"
        + (f" The served model uses {served_t:.2f} (`src/lib/intent-model-{args.embedding}.json`)." if served_t is not None else ""), "",
        "| Wrong action | Acted on ambiguous | Threshold | Near-optimal range | Coverage | Wrong actions | Needless questions | Ambiguous asked | Mean cost |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        w = r["weights"]
        mark = " **(current)**" if w == current else ""
        lines.append(f"| {w[0]}{mark} | {w[1]} | {r['threshold']:.2f} | {r['band'][0]:.2f}–{r['band'][1]:.2f} | "
                     f"{pct(r['coverage'])} | {pct(r['wrong_action_rate'])} | {pct(r['needless_question_rate'])} | "
                     f"{pct(r['ambiguous_asked_rate'])} | {r['cost']:.3f} |")
    lines += ["", "_Weights are relative to a needless question (= 1). Coverage, wrong actions and needless questions are "
              "shares of clear validation phrases; ambiguous asked is the share of ambiguous ones where the model asked. "
              f"Near-optimal range: thresholds whose mean cost is within {NEAR} of the minimum, i.e. where the choice is "
              "flat. Validation scores are optimistic (D7), so read the shape, not the levels._", ""]
    out = ti.ROOT / "reports" / f"cost_sensitivity_{args.embedding}.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ti.ROOT)}: thresholds {chosen}; served {served_t}")


if __name__ == "__main__":
    main()
