"""Choose the fraud-score cutoff for the policy engine (build step 12) and check it on held-out months.

The live system reads only `fraud_score`, which a bank has at dispute time (computed by the fraud engine at
authorization). `is_fraud` is used here, offline, as the answer key: in reality it only exists after disputes and
chargebacks are resolved, so the app never reads it (docs/policy.md PL-6).

Selection rule, fixed before the first run (commit it before running, like the sealed intent test set):
  - Population: debits a customer can dispute (every transaction type except Deposit).
  - Choose on transactions dated before 2026-01-01; hold out 2026 (2026-01-01 .. last day) for the check.
  - Cutoff = the LOWEST whole number c in 1..99 such that, on the choosing period, at least half of the
    transactions with fraud_score >= c are fraud. Lowest, because each point higher only misses more fraud;
    "at least half" means most hand-offs sent to an agent for this reason are real fraud.
  - Report on both periods: transactions flagged (total and per day), fraud caught (recall), hand-offs that are
    fraud (precision), plus the same by transaction type and a table of nearby cutoffs for context.

Run: uv run python pipeline/fraud_threshold.py   (needs data/processed/bronze.duckdb from pipeline/bronze.py)
Writes reports/fraud_threshold.md. Do not edit the report by hand.
"""
import duckdb
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "data" / "processed" / "bronze.duckdb"
OUT = ROOT / "reports" / "fraud_threshold.md"
SPLIT_DATE = "2026-01-01"
MIN_PRECISION = 0.5
CONTEXT_CUTOFFS = [20, 25, 28, 29, 30, 31, 32, 35, 40, 50, 70]

BASE = f"""
  select try_cast(fraud_score as double) as s,
         lower(is_fraud) = 'true' as f,
         transaction_type as t,
         cast(substr(transaction_date, 1, 10) as date) as d,
         cast(substr(transaction_date, 1, 10) as date) < date '{SPLIT_DATE}' as choose
  from transactions
  where transaction_type <> 'Deposit' and try_cast(fraud_score as double) is not null
"""


def metrics(con, cutoff: int, period: bool, by_type: bool = False):
    group = "t," if by_type else ""
    return con.sql(f"""
      with b as ({BASE})
      select {group}
        count(*) as n,
        sum(case when f then 1 else 0 end) as frauds,
        sum(case when s >= {cutoff} then 1 else 0 end) as flagged,
        sum(case when s >= {cutoff} and f then 1 else 0 end) as flagged_fraud,
        datediff('day', min(d), max(d)) + 1 as days
      from b where choose = {str(period).lower()}
      {"group by t order by t" if by_type else ""}
    """).fetchall()


def fmt_row(label, n, frauds, flagged, flagged_fraud, days):
    recall = 100 * flagged_fraud / frauds if frauds else 0
    precision = 100 * flagged_fraud / flagged if flagged else 0
    return (f"| {label} | {n:,} | {flagged:,} | {flagged / days:.2f} | {flagged_fraud:,} of {frauds:,} "
            f"({recall:.1f}%) | {precision:.1f}% |")


def main() -> None:
    con = duckdb.connect(str(DB), read_only=True)

    chosen = None
    for c in range(1, 100):
        (_, _, flagged, flagged_fraud, _), = metrics(con, c, True)
        if flagged and flagged_fraud / flagged >= MIN_PRECISION:
            chosen = c
            break
    if chosen is None:
        raise SystemExit("No cutoff reaches the precision target on the choosing period")

    head = "| | Transactions | Flagged (score ≥ cutoff) | Flagged per day | Fraud caught | Flagged that are fraud |\n|---|---|---|---|---|---|"
    lines = [
        "# Fraud-score cutoff for hand-off (build step 12)",
        "",
        "_Generated by `pipeline/fraud_threshold.py` from `data/processed/bronze.duckdb`. Do not edit by hand._",
        "",
        f"**Chosen cutoff: fraud_score ≥ {chosen}** (lowest whole number where at least {MIN_PRECISION:.0%} of flagged "
        f"debits are fraud, chosen on transactions before {SPLIT_DATE}; 2026 held out).",
        "",
        "Population: every transaction type except Deposit. `is_fraud` is the answer key here only; the app never reads it.",
        "",
        f"## Chosen period vs held-out 2026, at cutoff {chosen}",
        "",
        head,
        fmt_row(f"Chosen on: before {SPLIT_DATE}", *metrics(con, chosen, True)[0]),
        fmt_row(f"Held out: {SPLIT_DATE} onward", *metrics(con, chosen, False)[0]),
        "",
        f"## Held-out 2026 by transaction type, at cutoff {chosen}",
        "",
        head.replace("| |", "| Type |", 1),
        *[fmt_row(row[0], *row[1:]) for row in metrics(con, chosen, False, by_type=True)],
        "",
        "## Nearby cutoffs on the held-out period (context, not used to choose)",
        "",
        head.replace("| |", "| Cutoff |", 1),
        *[fmt_row(f"≥ {c}", *metrics(con, c, False)[0]) for c in CONTEXT_CUTOFFS],
        "",
        "## Reading it",
        "",
        "- The cutoff is set where normal transactions end. In this synthetic data that edge is unusually sharp; with real "
        "data the trade-off is gradual and the cutoff would be set by agent capacity and rechecked against confirmed disputes.",
        "- Fraud below the cutoff is not caught by this rule. Other signals (no matching transaction, the customer asking "
        "for a person) still route cases to an agent.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"chosen cutoff {chosen}; wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
