"""Projected agent time the Dispute Desk could take off agents, and what it costs (a projection, not a measurement).

Combines the organizer's contact-centre data (data/processed/bronze.duckdb) with the evaluation of the deployed app
(reports/eval_production-cohere.md) and writes reports/impact_estimate.md. Every assumption is printed in the report;
docs/impact.md explains them.

    uv run python analysis/impact_estimate.py                      # dollar table at illustrative hourly costs
    uv run python analysis/impact_estimate.py --cost-per-hour 12   # also a line at a cost you can cite
"""
import argparse
import re
from datetime import datetime, timezone
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "data" / "processed" / "bronze.duckdb"
EVAL = ROOT / "reports" / "eval_production-cohere.md"
OUT = ROOT / "reports" / "impact_estimate.md"

DISPUTE_CATEGORIES = ("Transactions", "Fees")  # "Cargo no reconocido" + "Cobro indebido", incl. rows missing a subcategory
CHAT_CHANNELS = ("App", "Web Chat", "WhatsApp")  # channels where a chat assistant can answer; not Phone, Email or Web forms
ILLUSTRATIVE_COSTS = (5, 10, 15, 20)  # USD per loaded agent hour; the dataset has no wage or cost data


def eval_metric(text: str, name: str) -> float:
    """First percentage or dollar value on the report row whose first cell starts with `name`."""
    row = next(line for line in text.splitlines() if line.startswith(f"| {name}"))
    m = re.search(r"\|\s*\$?([\d.]+)%?", row[len(name) + 2:])
    return float(m.group(1))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cost-per-hour", type=float, help="loaded cost of one agent hour in USD, if you have a real figure")
    args = ap.parse_args()

    con = duckdb.connect(str(DB), read_only=True)
    years = con.sql("""select date_diff('day', min(interaction_date::timestamp), max(interaction_date::timestamp)) / 365.25
                       from call_center_interactions""").fetchone()[0]
    # Agent hours per reason. duration_seconds is missing in ~14% of rows at random (as in contact_reasons.py), so the observed
    # sum is scaled by contacts / contacts-with-duration instead of counting missing calls as zero minutes.
    total_h, quejas, queja_h, missing = con.sql("""
        with r as (select reason_category, count(*) n, count(duration_seconds) n_dur, sum(duration_seconds::double) s
                   from call_center_interactions group by 1)
        select sum(s * n / n_dur) / 3600,
               max(n) filter (where reason_category = 'Queja'),
               max(s * n / n_dur) filter (where reason_category = 'Queja') / 3600,
               1 - max(n_dur::double / n) filter (where reason_category = 'Queja')
        from r""").fetchone()
    dispute_share, n_complaints, n_disputes = con.sql(f"""
        select avg((category in {DISPUTE_CATEGORIES})::int), count(*), sum((category in {DISPUTE_CATEGORIES})::int)
        from complaints""").fetchone()
    chat_share = con.sql(f"""
        select avg((channel in {CHAT_CHANNELS})::int) from call_center_interactions where reason_category = 'Queja'
        """).fetchone()[0]

    ev = EVAL.read_text()
    attempted = eval_metric(ev, "Automation attempted") / 100
    containment = eval_metric(ev, "Containment") / 100
    cost_res = eval_metric(ev, "Cost per successful resolution")
    cost_att = eval_metric(ev, "Cost per attempted case")

    per_year = lambda x: x / years  # noqa: E731
    dispute_h = per_year(queja_h) * dispute_share
    dispute_contacts = per_year(quejas) * dispute_share
    all_h = per_year(total_h)
    scenarios = [("Conservative: the share the system resolved itself in the evaluation", attempted),
                 ("Evaluation containment: ended without a person", containment)]

    lines = [
        "# Impact estimate: agent time and cost",
        "",
        f"_Generated by `analysis/impact_estimate.py` on {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC. Do not edit by hand._",
        "",
        "**A projection, not a measurement.** The agent-time figures come from the organizer's historical contact data; the share",
        "the system can handle comes from the offline evaluation of the deployed app on team-written, LLM-drafted and synthetic",
        "conversations. Nothing here was observed in production. Assumptions are listed at the end and explained in",
        "[docs/impact.md](../docs/impact.md).",
        "",
        "## Where the agent time goes today",
        "",
        "| | Total | Per year |",
        "|---|---:|---:|",
        f"| Period covered | {years:.2f} years | |",
        f"| All agent time (missing durations filled in) | {total_h:,.0f} h | {all_h:,.0f} h |",
        f"| Complaint contacts (`Queja`) | {quejas:,} | {per_year(quejas):,.0f} |",
        f"| Agent time on complaints | {queja_h:,.0f} h | {per_year(queja_h):,.0f} h |",
        f"| Money disputes as a share of complaints (PQR system) | {dispute_share:.1%} ({n_disputes:,} of {n_complaints:,}) | |",
        f"| **Dispute contacts and agent time** (complaints × dispute share) | | **{dispute_contacts:,.0f} contacts, {dispute_h:,.0f} h** ({dispute_h / all_h:.1%} of all agent time) |",
        f"| Complaint contacts in chat-capable channels ({', '.join(CHAT_CHANNELS)}) | {chat_share:.1%} | |",
        "",
        "## Projected agent time the system takes off agents",
        "",
        "| Scenario | Share handled without a person | Disputes move to chat: hours/year | Today's channel mix: hours/year |",
        "|---|---:|---:|---:|",
    ]
    for name, share in scenarios:
        saved = dispute_h * share
        lines.append(f"| {name} | {share:.1%} | **{saved:,.0f} h** ({saved / all_h:.1%} of all agent time) "
                     f"| {saved * chat_share:,.0f} h |")
    lo, hi = dispute_h * attempted, dispute_h * containment
    yearly_lo, yearly_hi = dispute_contacts * cost_att, dispute_contacts * cost_res
    lines += [
        "",
        "Hand-offs also reach the agent with verified facts and a briefing, so details aren't collected twice; that saving",
        "was not measured and is not counted here.",
        "",
        "## What it costs",
        "",
        "| | Value |",
        "|---|---:|",
        f"| Model cost per attempted case (evaluation) | ${cost_att:.4f} |",
        f"| Model cost per successful resolution (evaluation) | ${cost_res:.4f} |",
        f"| Model cost for every dispute contact in a year | ${yearly_lo:,.0f} – ${yearly_hi:,.0f} |",
        "",
        "Model cost is Claude Haiku (replies and extraction). Not included: Cohere embedding calls (fractions of a cent per",
        "message) and hosting (free tiers today; a production deployment costs more).",
        "",
        "## Agent time in dollars (illustrative)",
        "",
        "The dataset has no wage or cost data, so dollars depend on the loaded cost of an agent hour. Savings scale linearly.",
        "",
        "| Loaded cost per agent hour | Disputes move to chat (conservative – containment) | Today's channel mix |",
        "|---:|---:|---:|",
    ]
    costs = list(ILLUSTRATIVE_COSTS) + ([args.cost_per_hour] if args.cost_per_hour else [])
    for c in costs:
        tag = " (given)" if args.cost_per_hour and c == args.cost_per_hour else ""
        lines.append(f"| ${c:g}{tag} | ${lo * c:,.0f} – ${hi * c:,.0f} | ${lo * c * chat_share:,.0f} – ${hi * c * chat_share:,.0f} |")
    lines += [
        "",
        "## Assumptions",
        "",
        f"1. Disputes take the same share of complaint *contacts and agent time* ({dispute_share:.1%}) as they do of complaint",
        "   *cases* in the PQR system. The two tables aren't linked (data issue C2), so this is a proxy.",
        f"2. The evaluation's mix of conversations stands in for real dispute traffic: {attempted:.1%} resolved by the system",
        f"   (conservative) to {containment:.1%} ended without a person. The real mix is unknown.",
        "3. A contained conversation saves the whole agent handle time of that contact (follow-ups not counted separately).",
        f"4. Agent time is counted only where the assistant can answer: disputes moving to chat, or today's {chat_share:.1%}",
        "   of complaint contacts already in App, Web Chat or WhatsApp.",
        f"5. Missing call durations ({missing:.1%} of complaint contacts) are filled with their reason's average.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {lo:,.0f}–{hi:,.0f} agent-hours/year if disputes move to chat")


if __name__ == "__main__":
    main()
